/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.electronicmedicalrecords;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Carl Stephen
 */
public class ConsultationFrame extends javax.swing.JFrame {
    HealthcareSystem x = Main.system;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultationFrame.class.getName());

    /**
     * Creates new form ConsultationFrame
     */
    public ConsultationFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private String generateVisitID() {
        int visitNumber = x.countVisits() + 1;
        return ("V" + visitNumber);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalFeeField = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        patientNameField = new javax.swing.JTextField();
        visitDateField = new javax.swing.JTextField();
        symptomsField = new javax.swing.JTextField();
        diagnosisField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        prescriptionField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        doctorField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        serviceFeeField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        medicineFeeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultation");

        totalFeeField.setBackground(new java.awt.Color(235, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Consultation");

        jLabel4.setText("Name:");

        jLabel5.setText("Visit Date:");

        jLabel6.setText("Symptoms:");

        jLabel7.setText("Diagnosis:");

        backButton.setBackground(new java.awt.Color(64, 196, 193));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        saveButton.setBackground(new java.awt.Color(64, 196, 193));
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        patientNameField.addActionListener(this::patientNameFieldActionPerformed);

        visitDateField.addActionListener(this::visitDateFieldActionPerformed);

        symptomsField.addActionListener(this::symptomsFieldActionPerformed);

        diagnosisField.addActionListener(this::diagnosisFieldActionPerformed);

        jLabel13.setText("Prescription");

        prescriptionField.addActionListener(this::prescriptionFieldActionPerformed);

        jLabel14.setText("Doctor:");

        doctorField.addActionListener(this::doctorFieldActionPerformed);

        jLabel15.setText("Service Fee:");

        serviceFeeField.addActionListener(this::serviceFeeFieldActionPerformed);

        jLabel16.setText("Medicine Fee:");

        medicineFeeField.addActionListener(this::medicineFeeFieldActionPerformed);

        javax.swing.GroupLayout totalFeeFieldLayout = new javax.swing.GroupLayout(totalFeeField);
        totalFeeField.setLayout(totalFeeFieldLayout);
        totalFeeFieldLayout.setHorizontalGroup(
            totalFeeFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalFeeFieldLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(totalFeeFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(totalFeeFieldLayout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(totalFeeFieldLayout.createSequentialGroup()
                        .addGroup(totalFeeFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(symptomsField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(visitDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diagnosisField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addGroup(totalFeeFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(medicineFeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serviceFeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(doctorField)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(95, 95, 95))
        );

        totalFeeFieldLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {diagnosisField, doctorField, medicineFeeField, patientNameField, prescriptionField, serviceFeeField, symptomsField, visitDateField});

        totalFeeFieldLayout.setVerticalGroup(
            totalFeeFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalFeeFieldLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(totalFeeFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totalFeeFieldLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceFeeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicineFeeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(totalFeeFieldLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visitDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(symptomsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(totalFeeFieldLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diagnosisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(totalFeeFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalFeeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalFeeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        DashboardFrame dash = new DashboardFrame();
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String visitID = generateVisitID();
        String patientID = null;
        String patientName = patientNameField.getText();
        String visitDate = visitDateField.getText();
        String symptoms = symptomsField.getText();
        String diagnosis = diagnosisField.getText();
        String prescription = prescriptionField.getText();
        String doctor = doctorField.getText();
        String serviceFee = serviceFeeField.getText();
        String medicineFee = medicineFeeField.getText();
        
        MasterNode p = x.headMaster;
        
        while (p != null) {
            if (patientName.equals(p.patientName)) {
                patientID = p.patientID;
                break;
            }
            p = p.next;
        }
        
        if (patientID == null) {
            JOptionPane.showMessageDialog(this, "Patient not yet registered");
            return;
        }
        
        try {
            if (patientName.isEmpty() || visitDate.isEmpty() || symptoms.isEmpty() || diagnosis.isEmpty() || prescription.isEmpty() || doctor.isEmpty() || serviceFee.isEmpty() || medicineFee.isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields are required!");
                return;
            }
            
            double sf = Double.parseDouble(serviceFee);
            double mf = Double.parseDouble(medicineFee);
            double tf = mf + sf;
            
            x.addTransaction(visitID, patientID, patientName, sf, mf, tf, visitDate, symptoms, diagnosis, prescription, doctor);
            
            FileWriter fw = new FileWriter("C:\\Acads\\scar\\2nd year 2nd sem\\Programming Language\\ElectronicMedicalRecords\\src\\main\\java\\com\\mycompany\\electronicmedicalrecords\\transaction.txt", true);
            fw.write(
                visitID + "|" +
                patientID + "|" +
                patientName + "|" +
                visitDate + "|" +
                symptoms + "|" +
                diagnosis + "|" +
                prescription + "|" +
                doctor + "|" +
                sf + "|" +
                mf + "|" +
                tf + "\n"
            );
            fw.close();

            JOptionPane.showMessageDialog(this,"Total Fee: " + tf + "\nConsultation Successfully Saved!");
            DashboardFrame dash = new DashboardFrame();
            dash.setVisible(true);
            this.dispose();
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Fees Must be Numbers!");
        } catch (IOException ex){
            JOptionPane.showMessageDialog(this, "Error Saving Transaction.txt");
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void patientNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameFieldActionPerformed

    private void visitDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitDateFieldActionPerformed

    private void symptomsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symptomsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symptomsFieldActionPerformed

    private void diagnosisFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosisFieldActionPerformed

    private void prescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prescriptionFieldActionPerformed

    private void doctorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorFieldActionPerformed

    private void serviceFeeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceFeeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceFeeFieldActionPerformed

    private void medicineFeeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineFeeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineFeeFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultationFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField diagnosisField;
    private javax.swing.JTextField doctorField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField medicineFeeField;
    private javax.swing.JTextField patientNameField;
    private javax.swing.JTextField prescriptionField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField serviceFeeField;
    private javax.swing.JTextField symptomsField;
    private javax.swing.JPanel totalFeeField;
    private javax.swing.JTextField visitDateField;
    // End of variables declaration//GEN-END:variables
}
